[package]
name = "hunt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
regex = "1.10"
walkdir = "2.4"
indicatif = "0.17"
colored = "2.1"
